//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// pg0edit.rc で使用
//
#define IDS_STRING_OPEN_TITLE           10
#define IDS_STRING_SAVE_TITLE           11
#define IDS_STRING_MSG_MODIFY           12
#define IDS_STRING_CONSOLE_START        13
#define IDS_STRING_CONSOLE_END          14
#define IDS_STRING_CONSOLE_STOP         15
#define IDS_STRING_CONSOLE_RESULT       16
#define IDS_STRING_HEADER_NAME          17
#define IDS_STRING_HEADER_VALUE         18
#define IDS_STRING_CONFIRM_TUTORIAL     19
#define IDS_STRING_ONLINE_OPEN_TITLE    20
#define IDS_STRING_ONLINE_SAVE_TITLE    21
#define IDS_STRING_ONLINE_HISTORY_TITLE 22
#define IDS_STRING_ONLINE_COPY          23
#define IDS_STRING_ONLINE_COPY_AUTORUN  24
#define IDS_STRING_ONLINE_REMOVE        25
#define IDS_STRING_ONLINE_REMOVE_PASSWORD 26
#define IDS_STRING_ONLINE_READ_MORE     27
#define IDS_STRING_ONLINE_HISTORY_CURRENT 28
#define IDS_STRING_ONLINE_FILTER_ALL    29
#define IDS_STRING_ONLINE_FILTER_MINE   30
#define IDS_STRING_ONLINE_SORT_POPULAR  31
#define IDS_STRING_ONLINE_SORT_NEW      32
#define IDS_STRING_ONLINE_TAG_GAME      33
#define IDS_STRING_ONLINE_TAG_GRAPHICS  34
#define IDS_STRING_ONLINE_TAG_MATH      35
#define IDS_STRING_ONLINE_TAG_ALGORITHM 36
#define IDS_STRING_ONLINE_TAG_TEXT      37
#define IDS_STRING_ONLINE_TAG_STUDY     38
#define IDS_STRING_ONLINE_TAG_TOOL      39
#define IDS_STRING_ONLINE_TAG_OTHER     40
#define IDS_STRING_ONLINE_FILE          41
#define IDS_STRING_ONLINE_AUTHOR        42
#define IDS_STRING_ONLINE_PASSWORD      43
#define IDS_STRING_ONLINE_MEMO          44
#define IDS_STRING_ONLINE_TAGS          45
#define IDS_STRING_ONLINE_SAVE_NEW      46
#define IDS_STRING_ONLINE_PRIVATE       47
#define IDS_STRING_ONLINE_SAVE_BUTTON   48
#define IDS_STRING_ONLINE_CANCEL_BUTTON 49
#define IDS_STRING_ONLINE_OK_BUTTON     50
#define IDS_STRING_ONLINE_CONFIRM_PRIVATE 51
#define IDS_STRING_ONLINE_ERROR_UNAUTHORIZED 52
#define IDS_STRING_ONLINE_ERROR_NOT_FOUND 53
#define IDS_STRING_ONLINE_ERROR_CONNECTION 54
#define IDS_STRING_ONLINE_ERROR_CONFLICT 55
#define IDS_STRING_ONLINE_ERROR_NAME_TOO_LONG 56
#define IDS_STRING_ONLINE_ERROR_AUTHOR_TOO_LONG 57
#define IDS_STRING_ONLINE_ERROR_NAME_NOT_ENTERED 58
#define IDS_STRING_ONLINE_ERROR_AUTHOR_NOT_ENTERED 59
#define IDS_STRING_ONLINE_ERROR_PASSWORD_NOT_ENTERED 60
#define IDS_STRING_ONLINE_SEARCH        61
#define IDI_ICON_MAIN                   102
#define IDR_MENU                        103
#define IDR_ACCELERATOR                 106
#define IDR_TOOLBAR                     107
#define IDR_TOOLBAR_64                  108
#define IDR_TOOLBAR_96                  109
#define ID_MENUITEM_OPEN                40001
#define ID_MENUITEM_SAVEAS              40002
#define ID_MENUITEM_CLOSE               40003
#define ID_MENUITEM_UNDO                40009
#define ID_MENUITEM_REDO                40010
#define ID_MENUITEM_COPY                40011
#define ID_MENUITEM_CUT                 40012
#define ID_MENUITEM_PASTE               40013
#define ID_MENUITEM_DELETE              40014
#define ID_MENUITEM_SELECT_ALL          40015
#define ID_MENUITEM_FONT                40016
#define ID_MENUITEM_WORDWRAP            40017
#define ID_MENUITEM_SAVE                40018
#define ID_MENUITEM_NEW                 40019
#define ID_MENUITEM_EXEC                40020
#define ID_MENUITEM_CLEAR               40021
#define ID_MENUITEM_STOP                40022
#define ID_MENUITEM_NO_WAIT             40023
#define ID_MENUITEM_SPEED_HIGH          40024
#define ID_MENUITEM_SPEED_MID           40025
#define ID_MENUITEM_SPEED_LOW           40026
#define ID_MENUITEM_STEP                40027
#define ID_BUTTON_RUN                   40029
#define ID_BUTTON_STEP                  40031
#define ID_BUTTON_STOP                  40032
#define ID_MENUITEM_RUN_TO_CURSOR       40034
#define ID_MENUITEM_ABOUT               40035
#define ID_MENUITEM_TUTORIAL            40036
#define ID_MENUITEM_PG05                40037
#define ID_MENUITEM_FIND                40041
#define ID_MENUITEM_FINDNEXT            40045
#define ID_MENUITEM_LINE_NO             40046
#define ID_MENUITEM_ONLINE_OPEN         40053
#define ID_MENUITEM_ONLINE_SAVE         40054
#define ID_MENUITEM_ONLINE_HISTORY      40055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40056
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
