/*
 * PG0
 *
 * script_image.c
 *
 * Copyright (C) 1996-2026 by Nakashima Tomoaki. All rights reserved.
 *		https://www.nakka.com/
 *		nakka@nakka.com
 *
 * The parse tree written to / read from a binary image, so that a program
 * generated by pg0gen can run a script without the parser.
 *
 * Image format (little endian, strings are int32 length + UTF-16 characters, -1 = NULL):
 *   "PG0I", int32 version
 *   int32 library count, string dll name...
 *   int32 script count, script...
 *     string name, int32 strict_val, int32 extension, int32 exec_seq
 *     int32 token count, token... (in depth-first order: a token, its target block, then next)
 *       int32 sym_type, string buf, int32 i, double f, int32 line,
 *       int32 next, int32 target, int32 link (token index, -1 = NULL)
 *     int32 function count, function... (string name, int32 token index)
 */

/* Include Files */
#include <windows.h>
#include <tchar.h>

#include "script.h"
#include "script_string.h"
#include "script_memory.h"
#include "script_image.h"

#ifndef UNICODE
#error script_image.c requires a Unicode build (strings are stored as UTF-16)
#endif

/* Define */
#define IMAGE_MAGIC				"PG0I"
#define IMAGE_VERSION			1
#define IMAGE_MAX_COUNT			(16 * 1024 * 1024)

/* Struct */
// growing output buffer
typedef struct _WRITER {
	BYTE *buf;
	DWORD size;
	DWORD capacity;
	BOOL error;
} WRITER;

// bounds checked input
typedef struct _READER {
	const BYTE *buf;
	DWORD size;
	DWORD pos;
	BOOL error;
} READER;

// tokens of one script in depth-first order
typedef struct _TOKENLIST {
	TOKEN **tk;
	int count;
	int capacity;
} TOKENLIST;

// token pointer -> index, sorted by pointer
typedef struct _TOKENREF {
	TOKEN *tk;
	int index;
} TOKENREF;

/* Global Variables */

/* Local Function Prototypes */
static BOOL w_bytes(WRITER *w, const void *p, DWORD n);
static void w_int(WRITER *w, int v);
static void w_double(WRITER *w, double v);
static void w_str(WRITER *w, const TCHAR *s);
static BOOL r_bytes(READER *r, void *p, DWORD n);
static int r_int(READER *r);
static double r_double(READER *r);
static TCHAR *r_str(READER *r);
static BOOL r_skip_str(READER *r);
static BOOL collect_tokens(TOKENLIST *list, TOKEN *tk);
static int compare_ref(const void *a, const void *b);
static int token_index(TOKENREF *ref, int count, TOKEN *tk);
static BOOL write_script(WRITER *w, SCRIPTINFO *sci);
static BOOL read_header(READER *r);
static int validate_tree(int *next, int *target, int count, int k);
static BOOL read_script(READER *r, SCRIPTINFO *sci);

/*
 * w_bytes - append bytes
 */
static BOOL w_bytes(WRITER *w, const void *p, DWORD n)
{
	if (w->error) {
		return FALSE;
	}
	if (w->size + n > w->capacity) {
		DWORD capacity = (w->capacity == 0) ? 4096 : w->capacity * 2;
		BYTE *buf;
		while (capacity < w->size + n) {
			capacity *= 2;
		}
		// mem_realloc does not accept NULL
		buf = (w->buf == NULL) ? mem_alloc(capacity) : mem_realloc(w->buf, capacity);
		if (buf == NULL) {
			w->error = TRUE;
			return FALSE;
		}
		w->buf = buf;
		w->capacity = capacity;
	}
	CopyMemory(w->buf + w->size, p, n);
	w->size += n;
	return TRUE;
}

static void w_int(WRITER *w, int v)
{
	w_bytes(w, &v, sizeof(v));
}

static void w_double(WRITER *w, double v)
{
	w_bytes(w, &v, sizeof(v));
}

static void w_str(WRITER *w, const TCHAR *s)
{
	int len;

	if (s == NULL) {
		w_int(w, -1);
		return;
	}
	len = lstrlen(s);
	w_int(w, len);
	w_bytes(w, s, sizeof(TCHAR) * len);
}

/*
 * r_bytes - read bytes
 */
static BOOL r_bytes(READER *r, void *p, DWORD n)
{
	if (r->error || n > r->size - r->pos) {
		r->error = TRUE;
		return FALSE;
	}
	CopyMemory(p, r->buf + r->pos, n);
	r->pos += n;
	return TRUE;
}

static int r_int(READER *r)
{
	int v = 0;

	r_bytes(r, &v, sizeof(v));
	return v;
}

static double r_double(READER *r)
{
	double v = 0;

	r_bytes(r, &v, sizeof(v));
	return v;
}

/*
 * r_str - read a string (allocated with mem_alloc, NULL for a NULL string or an error)
 */
static TCHAR *r_str(READER *r)
{
	TCHAR *s;
	int len;

	len = r_int(r);
	if (r->error || len < 0) {
		return NULL;
	}
	if ((DWORD)len > (r->size - r->pos) / sizeof(TCHAR)) {
		r->error = TRUE;
		return NULL;
	}
	s = mem_alloc(sizeof(TCHAR) * (len + 1));
	if (s == NULL) {
		r->error = TRUE;
		return NULL;
	}
	r_bytes(r, s, sizeof(TCHAR) * len);
	*(s + len) = TEXT('\0');
	return s;
}

static BOOL r_skip_str(READER *r)
{
	int len;

	len = r_int(r);
	if (r->error) {
		return FALSE;
	}
	if (len < 0) {
		return TRUE;
	}
	if ((DWORD)len > (r->size - r->pos) / sizeof(TCHAR)) {
		r->error = TRUE;
		return FALSE;
	}
	r->pos += sizeof(TCHAR) * len;
	return TRUE;
}

/*
 * collect_tokens - list the tokens in depth-first order (a token, its block, then the next token)
 */
static BOOL collect_tokens(TOKENLIST *list, TOKEN *tk)
{
	for (; tk != NULL; tk = tk->next) {
		if (list->count >= list->capacity) {
			int capacity = (list->capacity == 0) ? 256 : list->capacity * 2;
			TOKEN **buf = (list->tk == NULL) ? mem_alloc(sizeof(TOKEN *) * capacity) : mem_realloc(list->tk, sizeof(TOKEN *) * capacity);
			if (buf == NULL) {
				return FALSE;
			}
			list->tk = buf;
			list->capacity = capacity;
		}
		*(list->tk + list->count) = tk;
		list->count++;
		if (tk->target != NULL && collect_tokens(list, tk->target) == FALSE) {
			return FALSE;
		}
	}
	return TRUE;
}

static int compare_ref(const void *a, const void *b)
{
	const TOKENREF *ra = a, *rb = b;

	return (ra->tk < rb->tk) ? -1 : (ra->tk > rb->tk) ? 1 : 0;
}

/*
 * token_index - index of a token (-1 for NULL, -2 when it is not in the tree)
 */
static int token_index(TOKENREF *ref, int count, TOKEN *tk)
{
	int lo = 0, hi = count - 1;

	if (tk == NULL) {
		return -1;
	}
	while (lo <= hi) {
		int mid = (lo + hi) / 2;
		if ((ref + mid)->tk == tk) {
			return (ref + mid)->index;
		} else if ((ref + mid)->tk < tk) {
			lo = mid + 1;
		} else {
			hi = mid - 1;
		}
	}
	return -2;
}

/*
 * write_script - one script of the chain
 */
static BOOL write_script(WRITER *w, SCRIPTINFO *sci)
{
	TOKENLIST list;
	TOKENREF *ref = NULL;
	FUNCINFO *fi;
	BOOL ret = FALSE;
	int i, count;

	ZeroMemory(&list, sizeof(list));
	if (collect_tokens(&list, sci->tk) == FALSE) {
		goto end;
	}
	if (list.count > 0) {
		ref = mem_alloc(sizeof(TOKENREF) * list.count);
		if (ref == NULL) {
			goto end;
		}
		for (i = 0; i < list.count; i++) {
			(ref + i)->tk = *(list.tk + i);
			(ref + i)->index = i;
		}
		qsort(ref, list.count, sizeof(TOKENREF), compare_ref);
	}

	w_str(w, sci->name);
	w_int(w, sci->strict_val);
	w_int(w, sci->extension);
	w_int(w, sci->exec_seq);

	w_int(w, list.count);
	for (i = 0; i < list.count; i++) {
		TOKEN *tk = *(list.tk + i);
		int next = token_index(ref, list.count, tk->next);
		int target = token_index(ref, list.count, tk->target);
		int link = token_index(ref, list.count, tk->link);
		if (next < -1 || target < -1 || link < -1) {
			goto end;
		}
		w_int(w, tk->sym_type);
		w_str(w, tk->buf);
		w_int(w, tk->i);
		w_double(w, tk->f);
		w_int(w, tk->line);
		w_int(w, next);
		w_int(w, target);
		w_int(w, link);
	}

	for (count = 0, fi = sci->fi; fi != NULL; fi = fi->next, count++);
	w_int(w, count);
	for (fi = sci->fi; fi != NULL; fi = fi->next) {
		int index = token_index(ref, list.count, fi->tk);
		if (index < 0) {
			goto end;
		}
		w_str(w, fi->name);
		w_int(w, index);
	}
	ret = !w->error;
end:
	mem_free(&ref);
	mem_free((void **)&list.tk);
	return ret;
}

/*
 * ScriptToImage - the parse trees of a script chain and its libraries as an image
 */
BYTE *ScriptToImage(SCRIPTINFO *sci, DWORD *size)
{
	WRITER w;
	SCRIPTINFO *csci;
	LIBRARYINFO *lib;
	TCHAR path[MAX_PATH + 1];
	TCHAR *p, *r;
	int count;

	*size = 0;
	if (sci == NULL) {
		return NULL;
	}
	sci = sci->sci_top;
	ZeroMemory(&w, sizeof(w));
	w_bytes(&w, IMAGE_MAGIC, 4);
	w_int(&w, IMAGE_VERSION);

	// libraries (file names of the loaded DLLs)
	for (count = 0, lib = sci->lib; lib != NULL; lib = lib->next, count++);
	w_int(&w, count);
	for (lib = sci->lib; lib != NULL; lib = lib->next) {
		if (GetModuleFileName(lib->hModul, path, MAX_PATH) == 0) {
			mem_free(&w.buf);
			return NULL;
		}
		for (p = r = path; *p != TEXT('\0'); p++) {
			if (*p == TEXT('\\') || *p == TEXT('/')) {
				r = p + 1;
			}
		}
		w_str(&w, r);
	}

	// scripts
	for (count = 0, csci = sci; csci != NULL; csci = csci->next, count++);
	w_int(&w, count);
	for (csci = sci; csci != NULL; csci = csci->next) {
		if (write_script(&w, csci) == FALSE) {
			mem_free(&w.buf);
			return NULL;
		}
	}
	if (w.error) {
		mem_free(&w.buf);
		return NULL;
	}
	*size = w.size;
	return w.buf;
}

/*
 * read_header - check the magic and the version, leaving the reader at the library count
 */
static BOOL read_header(READER *r)
{
	char magic[4];

	if (r_bytes(r, magic, 4) == FALSE || memcmp(magic, IMAGE_MAGIC, 4) != 0) {
		return FALSE;
	}
	if (r_int(r) != IMAGE_VERSION || r->error) {
		return FALSE;
	}
	return TRUE;
}

/*
 * ImageLibraryCount - number of libraries recorded in an image (-1 for an invalid image)
 */
int ImageLibraryCount(const BYTE *buf, DWORD size)
{
	READER r;
	int count;

	ZeroMemory(&r, sizeof(r));
	r.buf = buf;
	r.size = size;
	if (read_header(&r) == FALSE) {
		return -1;
	}
	count = r_int(&r);
	if (r.error || count < 0) {
		return -1;
	}
	return count;
}

/*
 * ImageLibraryName - file name of a library recorded in an image
 */
BOOL ImageLibraryName(const BYTE *buf, DWORD size, int index, TCHAR *name, int name_size)
{
	READER r;
	TCHAR *s;
	int count, i;

	ZeroMemory(&r, sizeof(r));
	r.buf = buf;
	r.size = size;
	if (read_header(&r) == FALSE) {
		return FALSE;
	}
	count = r_int(&r);
	if (r.error || index < 0 || index >= count) {
		return FALSE;
	}
	for (i = 0; i < index; i++) {
		if (r_skip_str(&r) == FALSE) {
			return FALSE;
		}
	}
	s = r_str(&r);
	if (s == NULL) {
		return FALSE;
	}
	if (lstrlen(s) >= name_size) {
		mem_free(&s);
		return FALSE;
	}
	lstrcpy(name, s);
	mem_free(&s);
	return TRUE;
}

/*
 * validate_tree - the token list starting at k has the depth-first layout written by write_script
 * (returns the index following the list, or -1 when the layout is broken)
 */
static int validate_tree(int *next, int *target, int count, int k)
{
	int n;

	while (k != -1) {
		if (k < 0 || k >= count) {
			return -1;
		}
		n = k + 1;
		if (*(target + k) != -1) {
			if (*(target + k) != n) {
				return -1;
			}
			n = validate_tree(next, target, count, n);
			if (n < 0) {
				return -1;
			}
		}
		if (*(next + k) == -1) {
			return n;
		}
		if (*(next + k) != n) {
			return -1;
		}
		k = *(next + k);
	}
	return 0;
}

/*
 * read_script - one script of the chain into an initialized SCRIPTINFO
 */
static BOOL read_script(READER *r, SCRIPTINFO *sci)
{
	TOKEN **tk = NULL;
	int *next = NULL, *target = NULL, *link = NULL;
	FUNCINFO *fi, *pfi = NULL;
	BOOL ret = FALSE;
	BOOL tree = FALSE;
	int count = 0, fcount, i;

	sci->name = r_str(r);
	sci->strict_val = r_int(r);
	sci->extension = r_int(r);
	sci->exec_seq = r_int(r);

	// tokens
	count = r_int(r);
	if (r->error || count < 0 || count > IMAGE_MAX_COUNT) {
		return FALSE;
	}
	if (count > 0) {
		tk = mem_calloc(sizeof(TOKEN *) * count);
		next = mem_alloc(sizeof(int) * count);
		target = mem_alloc(sizeof(int) * count);
		link = mem_alloc(sizeof(int) * count);
		if (tk == NULL || next == NULL || target == NULL || link == NULL) {
			goto end;
		}
	}
	for (i = 0; i < count; i++) {
		TOKEN *t = mem_calloc(sizeof(TOKEN));
		if (t == NULL) {
			goto end;
		}
		*(tk + i) = t;
		t->sym_type = r_int(r);
		t->buf = r_str(r);
		t->i = r_int(r);
		t->f = r_double(r);
		t->line = r_int(r);
		*(next + i) = r_int(r);
		*(target + i) = r_int(r);
		*(link + i) = r_int(r);
		if (r->error) {
			goto end;
		}
	}
	if (count > 0) {
		if (validate_tree(next, target, count, 0) != count) {
			goto end;
		}
		for (i = 0; i < count; i++) {
			TOKEN *t = *(tk + i);
			if (*(link + i) < -1 || *(link + i) >= count) {
				goto end;
			}
			t->next = (*(next + i) == -1) ? NULL : *(tk + *(next + i));
			t->target = (*(target + i) == -1) ? NULL : *(tk + *(target + i));
			t->link = (*(link + i) == -1) ? NULL : *(tk + *(link + i));
		}
		// from here the tokens belong to the tree and are freed with it
		sci->tk = *tk;
		tree = TRUE;
	}

	// functions
	fcount = r_int(r);
	if (r->error || fcount < 0 || fcount > IMAGE_MAX_COUNT) {
		goto end;
	}
	for (i = 0; i < fcount; i++) {
		int index;
		fi = mem_calloc(sizeof(FUNCINFO));
		if (fi == NULL) {
			goto end;
		}
		if (pfi == NULL) {
			sci->fi = fi;
		} else {
			pfi->next = fi;
		}
		pfi = fi;
		fi->name = r_str(r);
		index = r_int(r);
		if (r->error || fi->name == NULL || index < 0 || index >= count) {
			goto end;
		}
		fi->name_hash = str2hash(fi->name);
		fi->tk = *(tk + index);
	}
	ret = TRUE;
end:
	if (tk != NULL && tree == FALSE) {
		// the tree was not built: free the tokens one by one
		for (i = 0; i < count; i++) {
			if (*(tk + i) != NULL) {
				mem_free(&(*(tk + i))->buf);
				mem_free(tk + i);
			}
		}
	}
	mem_free((void **)&tk);
	mem_free(&next);
	mem_free(&target);
	mem_free(&link);
	return ret;
}

/*
 * ImageToScript - the script chain of an image (the libraries are not loaded)
 */
SCRIPTINFO *ImageToScript(const BYTE *buf, DWORD size)
{
	READER r;
	SCRIPTINFO *sci = NULL, *csci, *psci = NULL;
	int count, i;

	ZeroMemory(&r, sizeof(r));
	r.buf = buf;
	r.size = size;
	if (read_header(&r) == FALSE) {
		return NULL;
	}
	// libraries
	count = r_int(&r);
	if (r.error || count < 0) {
		return NULL;
	}
	for (i = 0; i < count; i++) {
		if (r_skip_str(&r) == FALSE) {
			return NULL;
		}
	}
	// scripts
	count = r_int(&r);
	if (r.error || count <= 0 || count > IMAGE_MAX_COUNT) {
		return NULL;
	}
	for (i = 0; i < count; i++) {
		csci = mem_calloc(sizeof(SCRIPTINFO));
		if (csci == NULL) {
			FreeScriptInfo(sci);
			return NULL;
		}
		if (psci == NULL) {
			sci = csci;
		} else {
			psci->next = csci;
		}
		psci = csci;
		csci->sci_top = sci;
		if (read_script(&r, csci) == FALSE) {
			FreeScriptInfo(sci);
			return NULL;
		}
	}
	sci->strict_val_op = sci->strict_val;
	if (r.pos != r.size) {
		FreeScriptInfo(sci);
		return NULL;
	}
	return sci;
}
/* End of source */
